[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

# optional: only if you need Netlify Functions, adjust path accordingly
# functions = "../api"

# SPA routing so /anything loads index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
